### ISSUE TITLE
gtfstidy only writes output to a directory that already exists and is writeable

### ISSUE THREAD

**Issue by StevenMaude** [patrickbr/gtfstidy#1]
The help text says:

```
-o, --output string         gtfs output path, zip or directory (default "gtfs-out")
```

but gtfstidy only takes a directory as output, which is confusing.

Furthermore, there's no creation of a non-existent directory. If the destination directory, e.g. `gtfs-out/`, doesn't exist, then, e.g. with the data from [here](https://www.sfmta.com/about-sfmta/reports/gtfs-transit-data), you get:

```
$ gtfstidy -O google_transit.zip 
Removing unreferenced entries...
Error while writing GTFS feed in 'gtfs-out':
 Could not open required file agency.txt for writing
```

i.e. [this error from gtfswriter](https://github.com/patrickbr/gtfswriter/blob/6611e7b34260b4fcb432f5222b064195f2c53bc8/writer.go#L94).

(Would consider fixing myself, but not sure how you'd want all this resolving.)

**Comment by patrickbr** [comment]
I agree, this is confusing. I think the best way to fix this is to check for the existence of the directory in gtfstidy, remove the "zip" from the --help page, and later work on the ZIP output implementation in the gtfswriter.
