### ISSUE TITLE
Keep custom columns in files

### ISSUE THREAD

**Issue by Toppari** [patrickbr/gtfstidy#14]
Hi,

Would be it possible to stop gtfstidy from removing some custom column (not referenced in gtfs spec) e.g in stops.txt? Like if I would have column named "custom_id" in stops.txt, when running gtfstidy with some option it would not remove it.

**Comment by derhuerst** [comment]
Coincidentally, this would also solve #12 for me.

**Comment by hbruch** [comment]
+1 for a flag to keep custom columns, like e.g. `feed_info.feed_id`

**Comment by patrickbr** [comment]
`gtfstidy` now has the option `-F` to keep additional columns. I already added this option 2 years ago, but forgot to close this issue here. Sorry for that.
