### ISSUE TITLE
[Suggestion] Remove equivalent trips

### ISSUE THREAD

**Issue by brodyFlannigan** [patrickbr/gtfstidy#18]
GTFSTidy already removes trips that have the same arrival/departure times and the same service ID.

Would it be possible to do the same for trips that are identical save for their days of operation?

For instance:
Trips 1 and 2 are identical in terms of trip properties (stop_times, trip fields, etc.) except that trip 1's service is only in effect on Monday while Trip 2 is only on Tuesday.
What we should do is delete one of the two trips and assign the remaining one a new service_id that covers all the dates covered by the 2 original service IDs.

Would that be feasible? [OneBusAway's GTFS transformer does this with the calendar simplification option.](http://developer.onebusaway.org/modules/onebusaway-gtfs-modules/1.3.4-SNAPSHOT/onebusaway-gtfs-transformer-cli.html#Merge_Trips_and_Simplify_Calendar_Entries) and it can help reduce the size of a GTFS considerably.

**Comment by patrickbr** [comment]
Sorry for the extremely late reply here. `gtfstidy` already has this option. If you use `--remove-red-trips`, equivalent trips *with adjacent services* are combined into a single trip, if some additional requirements are fulfilled (these requirements all try to avoid creating complicated services).

If you additionally specify `--red-trips-aggressive`, equivalent trips are always combined, even if this means creating extremely complicated services with many exceptions.
