### ISSUE TITLE
Unclear parsing error for transfers

### ISSUE THREAD

**Issue by 2martens** [patrickbr/gtfstidy#19]
If I validate our feed using gtfstidy, it complains about an id collision in transfers. But I couldn't find any documentation about what the tool checks in order to come to that conclusion. 

The specific error message: ` ID collision, transfer 'de:02000:41951:1:419104' -> 'de:02000:41951:1:419104' already defined.`

Obviously, we have more than one transfer at that stop defined but each of these transfers involves a distinct combination of from and to trips. So I don't understand what is wrong.

**Comment by patrickbr** [comment]
This is because [gtfsparser](https://github.com/patrickbr/gtfsparser) does not support fields like `from_route_id` or `from_trip_id` in transfers.txt yet. I will push a commit for support of these additional fields over the weekend. This should immediately fix this issue.

**Comment by patrickbr** [comment]
Can you check again with the latest master? `from_route_id`, `to_route_id`, `from_trip_id` and `to_trip_id` should now be supported :)

**Comment by 2martens** [comment]
Will try that

**Comment by 2martens** [comment]
Works now and helped to find actual duplication.
