### ISSUE TITLE
gtfstidy removed quotes

### ISSUE THREAD

**Issue by Andi-Lo** [patrickbr/gtfstidy#2]
Hey there,

sadly the feature 

> Clean CSV output. Only quote string values where needed, use dynamic float precision, remove whitespace. Only output files that are necessary.

causes me trouble.

The original input (e.g. in agency.txt)
` "1","MBTA","http://www.mbta.com","America/New_York","EN","617-222-3200" `

will be parsed to:
` 3,MBTA,http://www.mbta.com,America/New_York,EN,617-222-3200 `

I think it makes sense to remove the quotes however it may not fit everyones needs.
In my case it will break my import script that I have to use.

Maybe that feature can be optional (CLI option flag) so the output format is the same as the input or maybe you can give me a hint for a work around in your gtfs csv-parser module.

Best wishes,
Andreas

**Comment by patrickbr** [comment]
The gtfswriter uses Go's standard csv.Writer, which complies with [RFC-4180](https://tools.ietf.org/html/rfc4180). It has no option to quote all fields, which is a reasonable decision as it keeps the code simple, yet standard compliant. The same goes for the gtfswriter: if I wanted to add this feature, I would have to write my own CSV writer. While this is a trivial thing to do, it would clutter the code and make maintainability harder. I want to avoid that.

I think you may be better of if you fixed your import script to correctly parse CSV files. If you don't have access to the code of this script, use a 3rd party tool to quote all fields. A quick Google search comes up with [this question on SA](http://stackoverflow.com/questions/17861958/how-to-double-quote-all-fields-in-a-text-file). I should be easy to integrate such a call in your transformation pipeline.
