### ISSUE TITLE
publish binaries for releases

### ISSUE THREAD

**Issue by derhuerst** [patrickbr/gtfstidy#4]
Would you mind publishing prebuilt binaries with every [release](https://github.com/patrickbr/gtfstidy/releases)?

If that's too much manual work, I would like to contribute a CI workflow that does this for every Git tag.

**Comment by patrickbr** [comment]
Why not, this should now be done for each tagged commit :) Thanks for the suggestion!

**Comment by derhuerst** [comment]
Thanks for publishing them! Is there a reason why macOS binaries are missing?

**Comment by patrickbr** [comment]
There isn't, and they are there now :D
