### ISSUE TITLE
Trips during the day hours missing

### ISSUE THREAD

**Issue by vishalmhjn** [patrickbr/gtfstidy#5]
I used this tool on the Free feed from gtfs.de with `-SCRmTcdsOeD` as arguments. The tool worked just fine. During the analysis, I found that trip_ids during the day were missing. I am not sure if this is intended to reduce file size (when headways between trips are not changing) or may a bug (as this is weird since the trips at all times should be there). 

Thank you

**Comment by patrickbr** [comment]
Strange. Are all day-hour trips missing? How did you determine that they were missing? Do have a concrete example? Thanks!

**Comment by vishalmhjn** [comment]
First, I analyzed one specific stop in the original feed:

stop_name | stop_id | stop_lat | stop_lon
Infanteriestraße | 205904 | 48.16146 | 11.5537

The filtered and sorted (by departure_time) stop_times are attached for both the original and gtfstidy output.


[feeds.zip](https://github.com/patrickbr/gtfstidy/files/5096424/feeds.zip)

Then I also compared the average stops in the feed using [this tutorial](http://simplistic.me/playing-with-gtfs.html) and found I think same problem exists for other stops as well

original feed:

<img width="725" alt="Screen Shot 2020-08-19 at 14 32 27" src="https://user-images.githubusercontent.com/42190624/90636333-bcaa4280-e22a-11ea-8164-b9d53580be43.png">

gtfs_tidy output
<img width="731" alt="Screen Shot 2020-08-19 at 14 44 38" src="https://user-images.githubusercontent.com/42190624/90636369-cb90f500-e22a-11ea-952f-348e10b150ad.png">

**Comment by patrickbr** [comment]
If you use the -T option, gtfstidy compresses stop times by searching for frequency covers. For example, if you have trips from A to B at 5:10, 6:10, 7:10, 8:10, 9:10, 10:10, ..., 23:10, gtfstidy will delete all these trips except the one starting at 5:10 and add an entry into the frequencies.txt describing that the trip will be repeated every 60 minutes. After skimming over the tutorial you linked, I don't think the frequencies.txt is used there.

**Comment by vishalmhjn** [comment]
Yes, it works as expected now, and you are right frequencies.txt is not used here. Thank you for your time. much appreciated :)

**Comment by patrickbr** [comment]
Great, thanks for the update!
