### ISSUE TITLE
v0.2 ?

### ISSUE THREAD

**Issue by christopheblin** [patrickbr/gtfstidy#7]
Hello,

The last tag 0.1 does not contain your latest changes, especially https://github.com/patrickbr/gtfstidy/commit/659ba4320fdc5735041f9186bf5d6b727c4f331c 

Do you plan to create a v0.2 soon ?

**Comment by patrickbr** [comment]
There is now a [v0.2](https://github.com/patrickbr/gtfstidy/releases/tag/v0.2) :)
