### ISSUE TITLE
Orphan deletion for calendar_dates is not removing unused exceptions

### ISSUE THREAD

**Issue by christopheblin** [patrickbr/gtfstidy#9]
The case is a bit tricky because the provided GTFS is absolutely messy

```
calendar_dates.txt /*the service 10213 will be used on the french holiday*/
service_id,date,exception_type
10213,20210714,1

calendar.txt /*does not contain 10213*/
service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
10000,1,1,1,1,1,0,0,20210630,20210709

trips.txt /*does not contain 10213 either*/
route_id,trip_id,service_id,trip_headsign,direction_id,wheelchair_accessible
016016010:10,125716436-1_485130,10000,PARC DES SOURCES,1,1
```

then you add the agency, route, 2 stops and 2 stoptimes for the trip in order to have something more or less valid GTFS

when gtfstidy is launched with -EAPICOS -s -c --keep-col-order, the calendar_dates still contains the exception

maybe service minimization is correctly removing these exceptions, however I need to keep the original services in order to understand real time data in the future

[gtfstidybug.zip](https://github.com/patrickbr/gtfstidy/files/6802717/gtfstidybug.zip)

```
/ # gtfstidy --fix -EAPICOS -s -c --keep-col-order -o gtfstidybug gtfstidybug
Parsing GTFS feed in 'gtfstidybug' ... done.
Removing unreferenced entries... done. (-0 trips [-0.00%], -0 stops [-0.00%], -0 shapes [-0.00%], -1 services [-49.98%], -0 routes [-0.00%], -0 agencies [-0.00%])
Removing redundant agencies... done. (-0 agencies [-0.00%])
Removing redundant stops... done. (-0 stops [-0.00%])
Reclustering stops... done. (-0 clusters) [-0.00%]
Remeasuring shapes... done. (0 shapes remeasured)
Minimizing shapes... done. (-0 shape points [-0.00%])
Removing redundant shapes... done. (-0 shapes [-0.00%])
Removing redundant trips... done. (-0 trips [-0.00%])
Removing unreferenced entries... done. (-0 trips [-0.00%], -0 stops [-0.00%], -0 shapes [-0.00%], -0 services [-0.00%], -0 routes [-0.00%], -0 agencies [-0.00%])
Removing service duplicates... done. (-0 services [-0.00%])
Minimizing services... done. (+0 calendar_dates.txt entries [+NaN%], +0 calendar.txt entries [+0.00%])
Outputting GTFS feed to 'gtfstidybug'... done.

/ # cat gtfstidybug/calendar_dates.txt 
service_id,date,exception_type
10213,20210714,1
```

**Comment by patrickbr** [comment]
Hm, I am not able to reproduce this. When I run

    $ gtfstidy -EAPICOS -s -c -z --keep-col-order -o tidied gtfstidybug.zip

service `10213` is correctly removed and no `calendar_dates.txt` is written.

Note that `gtfstidy` does not delete existing files, but only overwrites them. In particular, this means that if you read the GTFS files from a folder (i.e. not from a ZIP file) and write them back to the same folder, any input file that was empty in the output will still be present after the run. I think this is what's happening here.

I think `gtfstidy` should output a warning in this case and offer an option to delete GTFS files not belonging to the output feeds.

**Comment by christopheblin** [comment]
ah I see ! I always use gtfstidy "in place", I was not expecting that

the problem with that optional approach is that it is not consistent in behavior beween 2 different GTFS directories

for ex, if my calendar_dates.txt was
```
calendar_dates.txt
service_id,date,exception_type
10213,20210714,1
10000,20210714,1
```

then the file calendar_dates.txt would have been overwritten... so why is it not overwrtten when it becomes "empty" after a clean ?

so, in my opinion, deleting empty GTFS files from the output when they have been cleaned should not be a option but the default (it should not even be an option to keep files IMHO)

WDYT ?

**Comment by patrickbr** [comment]
I agree. With https://github.com/patrickbr/gtfswriter/commit/a5cf20236aba70535391af2bc8d0d6ff129c2204, gtfswriter (which is used in gtfstidy) deletes existing GTFS files from the target directory to guarantee consistency. After a `go get -u github.com/patrickbr/gtfstidy` you should see the expected behavior.
